# This configuration file assigns a specific LLM to each player agent.
# The GameMaster will read this file on startup.

player_setup:
  - player_id: 0
    model: "gpt-4-turbo"
  - player_id: 1
    model: "gemini/gemini-1.5-pro-latest"
  - player_id: 2
    model: "anthropic/claude-3-haiku-20240307"
  - player_id: 3
    model: "xai/grok-4-latest"
  - player_id: 4
    model: "deepseek/deepseek-chat"
  - player_id: 5
    model: "groq/llama3-8b-8192" # Using Groq for speed
  - player_id: 6
    model: "groq/llama3-8b-8192" # Using Groq for speed

# Role configuration for a 7-player game
roles:
  7:
    num_good: 4
    num_evil: 3
    roles: ["Merlin", "Percival", "Minion", "Morgana", "Loyal Servant", "Loyal Servant", "Loyal Servant"]
    evil_roles: ["Minion", "Morgana"]

# General game rules and context provided to the agents
game_rules: "This is The Resistance: Avalon. Follow the rules and your role's objectives."

role_contexts:
  Merlin: "You are Merlin. You know the agents of evil, but you must guide the loyal servants to victory without revealing your identity. If the assassin identifies you, evil wins."
  Percival: "You are Percival. You know the two players who are Merlin and Morgana, but you do not know which is which."
  Minion: "You are a Minion of Mordred. Your goal is to fail quests and ensure evil triumphs."
  Morgana: "You are Morgana. You appear as Merlin to Percival. Your goal is to confuse Percival and help evil win."
  Loyal Servant: "You are a Loyal Servant of Arthur. You must identify the minions and ensure that quests succeed."
